import Header from '@/components/Header'
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer' 
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Citas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
      </head>
      <body className={inter.className}>
        <div className='flex flex-col min-h-screen'>

          <Header />
          <div className='flex flex-grow'>
            <NavBar />
            <main className='flex-grow p-4'>
              {children}
            </main>
          </div>
         
          <Footer /> 
        </div>
      </body>
    </html>
  )
}
