
import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer' 
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Citas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        
      </head>
      <body className={inter.className}>

        <div className='flex flex-col min-h-screen'>
         <NavBar />
  
            <main className='flex-grow p-8'>
              {children}
            </main>
            
          <Footer /> 
        </div>
        
      </body>
    </html>
  )
}
