import NavBar from '../components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Citas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        
       <div className='flex h-[100vh]'>
       <NavBar/>

        {children}
      
       </div> 
        </body>
    </html>
  )
}
